# Generated by Django 4.0.9 on 2023-02-23 19:00

import connections.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_connectionunit_entity_connectionunit_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionunit',
            name='number',
            field=models.IntegerField(blank=True, default=connections.models.autoincrement, null=True, verbose_name='Порядковый номер интерфейса'),
        ),
    ]
