# Generated by Django 4.0.9 on 2023-02-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_alter_connectionunit_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectionunit',
            options={'ordering': ['id'], 'verbose_name': 'Интерфейс', 'verbose_name_plural': 'Интерфейсы'},
        ),
        migrations.AlterModelOptions(
            name='connectionunittype',
            options={'ordering': ['id'], 'verbose_name': 'Тип интерфейса', 'verbose_name_plural': 'Типы интерфейсов'},
        ),
    ]
