# Generated by Django 4.0.9 on 2023-03-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_alter_connectionunit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionunit',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Порядковый номер интерфейса'),
        ),
    ]
