# Generated by Django 4.0.9 on 2023-03-23 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_alter_connectionunit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionunit',
            name='children_node_connection_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_connection_unit', to='connections.connectionunit', verbose_name='Порт подчиненного логического устройства'),
        ),
    ]
