# Generated by Django 4.0.9 on 2023-03-23 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0007_alter_connectionunit_children_node_connection_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionunit',
            name='children_node_connection_unit',
        ),
        migrations.AddField(
            model_name='connectionunit',
            name='parent_node_connection_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_node_connection_unit', to='connections.connectionunit', verbose_name='Порт родительского логического устройства'),
        ),
    ]
