# Generated by Django 4.0.9 on 2023-03-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0008_remove_connectionunit_children_node_connection_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionunit',
            name='in_use_between_nodes',
            field=models.BooleanField(default=False, verbose_name='Используется для соединения оборудования'),
        ),
    ]
