# Generated by Django 4.0.9 on 2023-02-15 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус объекта',
                'verbose_name_plural': 'Статусы объектов',
            },
        ),
        migrations.AddField(
            model_name='abonent',
            name='object_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abonents.objectstatus', verbose_name='Статус'),
        ),
    ]
