# Generated by Django 4.0.9 on 2023-02-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonents', '0002_objectstatus_abonent_object_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonent',
            name='disable_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отключения'),
        ),
        migrations.AlterField(
            model_name='abonent',
            name='enable_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подключения'),
        ),
    ]
