# Generated by Django 4.0.9 on 2023-02-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonents', '0003_alter_abonent_disable_date_alter_abonent_enable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonent',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
