# Generated by Django 4.0.9 on 2023-02-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonents', '0004_alter_abonent_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonent',
            name='change_date',
            field=models.DateField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='abonent',
            name='contract',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='abonent',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
