# Generated by Django 4.0.9 on 2023-02-26 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_alter_building_options_alter_buildingtype_options_and_more'),
        ('abonents', '0007_alter_abonent_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonent',
            options={'ordering': ['id'], 'verbose_name': 'Абонент', 'verbose_name_plural': 'Абоненты'},
        ),
        migrations.AlterModelOptions(
            name='abonenttype',
            options={'ordering': ['id'], 'verbose_name': 'Тип абонента', 'verbose_name_plural': 'Типы абонентов'},
        ),
        migrations.AlterModelOptions(
            name='objectstatus',
            options={'ordering': ['id'], 'verbose_name': 'Статус объекта', 'verbose_name_plural': 'Статусы объектов'},
        ),
        migrations.AddField(
            model_name='abonent',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building', verbose_name='Здание'),
        ),
    ]
