# Generated by Django 4.0.9 on 2023-02-23 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('abonents', '0005_abonent_change_date_abonent_contract_abonent_phone'),
        ('services', '0003_alter_service_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='change_date',
            field=models.DateField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='service',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.entity', verbose_name='Сущность'),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abonents.objectstatus', verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='ServiceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Наименование')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Имя сервиса',
                'verbose_name_plural': 'Имена сервисов',
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicename'),
        ),
    ]
