# Generated by Django 4.0.9 on 2023-02-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['id'], 'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AlterModelOptions(
            name='servicename',
            options={'ordering': ['id'], 'verbose_name': 'Имя сервиса', 'verbose_name_plural': 'Имена сервисов'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['id'], 'verbose_name': 'Тип сервиса', 'verbose_name_plural': 'Типы сервисов'},
        ),
    ]
