# Generated by Django 4.0.9 on 2023-02-15 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип здания',
                'verbose_name_plural': 'Типы зданий',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=25, unique=True, verbose_name='Улица')),
                ('house', models.CharField(max_length=8, unique=True, verbose_name='Дом')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.buildingtype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
            },
        ),
    ]
