# Generated by Django 4.0.9 on 2023-02-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_regiontype_region_building_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiontype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование'),
        ),
    ]
