# Generated by Django 4.0.9 on 2023-02-15 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonents', '0002_objectstatus_abonent_object_status'),
        ('buildings', '0001_initial'),
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Наименование')),
                ('table', models.CharField(max_length=25, unique=True, verbose_name='Таблица')),
            ],
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': 'Логическое устройство', 'verbose_name_plural': 'Логические устройства'},
        ),
        migrations.RemoveField(
            model_name='node',
            name='name',
        ),
        migrations.AddField(
            model_name='node',
            name='buiilding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building', verbose_name='Здание'),
        ),
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abonents.objectstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='node',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodes.entity', verbose_name='Сущность'),
        ),
    ]
