# Generated by Django 4.0.9 on 2023-02-15 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('nodes', '0002_entity_alter_node_options_remove_node_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.entity', verbose_name='Сущность'),
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
