# Generated by Django 4.0.9 on 2023-02-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_alter_node_change_date_alter_node_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
    ]
