# Generated by Django 4.0.9 on 2023-02-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_node_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Наименование'),
        ),
    ]
