# Generated by Django 4.0.9 on 2023-02-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0006_node_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Наименование'),
        ),
    ]
