# Generated by Django 4.0.9 on 2023-02-25 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0011_nodename_alter_node_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodes.nodename', verbose_name='Наименование'),
        ),
    ]
