# Generated by Django 4.0.9 on 2023-02-25 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0012_alter_node_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodename',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodes.nodetype', verbose_name='Тип'),
        ),
    ]
