# Generated by Django 4.0.9 on 2023-02-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0013_nodename_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['id'], 'verbose_name': 'Логическое устройство', 'verbose_name_plural': 'Логические устройства'},
        ),
        migrations.AlterModelOptions(
            name='nodename',
            options={'ordering': ['id'], 'verbose_name': 'Имя оборудования', 'verbose_name_plural': 'Имена оборудования'},
        ),
        migrations.AlterModelOptions(
            name='nodetype',
            options={'ordering': ['id'], 'verbose_name': 'Тип оборудования', 'verbose_name_plural': 'Типы оборудования'},
        ),
    ]
